import { Link } from "react-router-dom";
import { ArrowUpRight, CalendarDays, Check, CheckCircle2, ChevronRight, Clock3, FolderKanban, ListTodo, Plus, Sparkles } from "lucide-react";
import AppLayout from "@/components/layout/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const calendarDays = ["26", "27", "28", "29", "30", "31", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "1", "2", "3", "4", "5", "6"];
const stats = [
  { label: "今日待办", value: "12", note: "3 项即将开始", icon: ListTodo, color: "bg-sky-50 text-sky-600", border: "border-sky-100" },
  { label: "设计中", value: "8", note: "本周新增 2 项", icon: Sparkles, color: "bg-violet-50 text-violet-600", border: "border-violet-100" },
  { label: "已完成", value: "24", note: "较上周 +15%", icon: CheckCircle2, color: "bg-emerald-50 text-emerald-600", border: "border-emerald-100" },
];

function SectionTitle({ icon: Icon, title, color, href }: { icon: typeof CalendarDays; title: string; color: string; href?: string }) {
  return <div className="flex items-center gap-2"><span className={cn("flex h-8 w-8 items-center justify-center rounded-lg", color)}><Icon className="h-4 w-4" /></span><h2 className="text-sm font-bold text-foreground">{title}</h2>{href && <Link to={href} className="ml-auto flex items-center gap-1 text-[11px] font-semibold text-muted-foreground hover:text-primary">查看全部<ChevronRight className="h-3 w-3" /></Link>}</div>;
}

export default function Index() {
  return <AppLayout title="设计工作台" subtitle="一个视图，掌握所有设计进展">
    <div className="mx-auto flex max-w-[1400px] flex-col gap-5">
      <section className="grid grid-cols-1 gap-4 sm:grid-cols-3">{stats.map((stat) => <div key={stat.label} className={cn("rounded-2xl border bg-card p-4 shadow-card", stat.border)}><div className="flex items-center justify-between"><span className={cn("flex h-9 w-9 items-center justify-center rounded-xl", stat.color)}><stat.icon className="h-[18px] w-[18px]" /></span><ArrowUpRight className="h-4 w-4 text-muted-foreground/50" /></div><p className="mt-3 text-2xl font-extrabold text-foreground">{stat.value}</p><div className="mt-1 flex items-center justify-between gap-2"><p className="text-xs font-semibold text-foreground">{stat.label}</p><span className="text-[10px] text-muted-foreground">{stat.note}</span></div></div>)}</section>

      <section className="grid grid-cols-1 gap-5 xl:grid-cols-12">
        <div className="rounded-2xl border border-border bg-card p-4 shadow-card sm:p-5 xl:col-span-7"><SectionTitle icon={CalendarDays} title="智能日历" color="bg-secondary text-primary" /><div className="mt-4 rounded-xl border border-border bg-card p-3"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-foreground">2025年5月</p><p className="mt-0.5 text-[10px] text-muted-foreground">本周有 4 个设计节点</p></div><div className="flex gap-1"><button className="rounded-lg bg-secondary px-2 py-1 text-[10px] text-muted-foreground">日</button><button className="rounded-lg bg-primary px-2 py-1 text-[10px] font-bold text-primary-foreground">月</button></div></div><div className="mt-4 grid grid-cols-7 gap-y-2 text-center text-[10px] text-muted-foreground">{["一","二","三","四","五","六","日"].map((d) => <span key={d}>{d}</span>)}{calendarDays.map((day, index) => <span key={`${day}-${index}`} className={cn("mx-auto flex h-6 w-6 items-center justify-center rounded-lg", day === "24" && index === 26 ? "bg-primary font-bold text-primary-foreground" : day === "20" && index === 22 ? "bg-accent font-bold text-accent-foreground" : index < 6 ? "text-muted-foreground/50" : "text-foreground")}>{day}</span>)}</div></div><div className="mt-3 flex items-center gap-3 rounded-xl border border-border bg-card p-3"><Clock3 className="h-4 w-4 text-primary" /><div><p className="text-xs font-bold text-foreground">今天 14:00 · 首页视觉稿评审会</p><p className="mt-0.5 text-[10px] text-muted-foreground">品牌重塑 2.0 · 会议室 A</p></div></div></div>
        <div className="rounded-2xl border border-border bg-card p-4 shadow-card sm:p-5 xl:col-span-5"><SectionTitle icon={ListTodo} title="待办事项" color="bg-secondary text-warning" href="/projects" /><div className="mt-4 space-y-2">{["首页视觉稿 v3 精修", "整理品牌色板与情绪板", "设计评审会 · 核心页面", "标注文档与切图交付"].map((item, index) => <div key={item} className="flex items-center gap-2.5 rounded-xl border border-border bg-card px-3 py-2.5"><span className={cn("flex h-4 w-4 items-center justify-center rounded-full border", index === 2 ? "border-primary bg-primary text-primary-foreground" : "border-border")}>{index === 2 && <Check className="h-2.5 w-2.5" />}</span><span className={cn("min-w-0 flex-1 truncate text-xs font-semibold", index === 2 ? "text-muted-foreground line-through" : "text-foreground")}>{item}</span><span className="text-[10px] text-muted-foreground">{index === 0 ? "今天" : index === 1 ? "明天" : "05/28"}</span></div>)}</div><Button asChild variant="outline" className="mt-4 h-9 w-full border-border bg-card text-xs hover:bg-secondary"><Link to="/projects"><Plus className="mr-1.5 h-3.5 w-3.5" />管理全部待办</Link></Button></div>
      </section>

      <section className="grid grid-cols-1 gap-5 xl:grid-cols-12">
        <div className="rounded-2xl border border-border bg-card p-4 shadow-card sm:p-5 xl:col-span-7"><SectionTitle icon={FolderKanban} title="设计项目一览" color="bg-secondary text-primary" href="/projects" /><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{ name: "品牌重塑 2.0", count: "4 个任务", progress: "68%", tone: "bg-primary" }, { name: "移动端体验升级", count: "8 个任务", progress: "42%", tone: "bg-sky-400" }, { name: "设计系统规范", count: "12 个任务", progress: "12%", tone: "bg-warning" }].map((project) => <Link key={project.name} to="/projects" className="rounded-xl border border-border bg-card p-3 transition-transform hover:-translate-y-0.5"><div className="flex items-center justify-between"><span className={cn("h-2 w-2 rounded-full", project.tone)} /><ArrowUpRight className="h-3.5 w-3.5 text-muted-foreground" /></div><p className="mt-4 text-xs font-bold text-foreground">{project.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{project.count}</p><div className="mt-3 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-secondary"><div className={cn("h-full rounded-full", project.tone)} style={{ width: project.progress }} /></div><span className="text-[10px] font-bold text-foreground">{project.progress}</span></div></Link>)}</div></div>
        <div className="rounded-2xl border border-border bg-card p-4 shadow-card sm:p-5 xl:col-span-5"><SectionTitle icon={Sparkles} title="项目详细信息" color="bg-accent text-accent-foreground" /><div className="mt-4 rounded-xl border border-border bg-card p-3.5"><div className="flex items-center justify-between"><Badge className="border-none bg-accent text-accent-foreground">即将开始</Badge><span className="text-[10px] text-muted-foreground">DSK-022</span></div><p className="mt-2 text-sm font-bold text-foreground">移动端适配与组件切图</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">任务将在明天开始，请提前准备移动端断点规范和组件导出清单。</p><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><CalendarDays className="h-3.5 w-3.5 text-primary" />05月25日 · 明天</span><span className="flex -space-x-1.5"><span className="flex h-6 w-6 items-center justify-center rounded-full border-2 border-white bg-primary text-[9px] font-bold text-primary-foreground">林</span><span className="flex h-6 w-6 items-center justify-center rounded-full border-2 border-white bg-accent text-[9px] font-bold text-accent-foreground">房</span></span></div></div><div className="mt-3 flex items-center gap-2 text-[10px] font-medium text-accent-foreground"><span className="h-1.5 w-1.5 rounded-full bg-accent-foreground" />还有 2 个任务即将开始或到期</div></div>
      </section>
    </div>
  </AppLayout>;
}
